config/routes.rb
Rails.application.routes.draw do
  get 'rank/show_rank'

  get 'rank/film_screens', as: :show_flim_screen_preference

  devise_for :users
  namespace :api do
    namespace :v1 , defaults: { format: :json } do
      resources :users, only: [:show, :create,:update]
      resources :sessions, only: [:create]
      resources :like, only: [:create]
      resources :dislike, only: [:create]
      resources :cinemas, only: [:index] do
      end
      get 'cinemas/current_films'
      get 'films/on_screen'=>'films#on_screen'
      post 'search_films'=>'films#search_films'
      get 'likes_and_dislikes'=>'films#likes_and_dislikes'
      get 'screen_preference'=>'screen#screen_preference'
      post 'screen_like'=>'screen#like_screen'
      post 'screen_dislike'=>'screen#dislike_screen'
      delete 'users/delete'=>'users#destroy'
      delete 'sessions/delete'=>'sessions#destroy'
      get 'is_user_sign_in'=>'users#is_user_sign_in'
      get 'my_liked_films'=>'films#my_liked_films'
      post 'set_default_cinema'=>'users#set_default_cinema'
    end
  end

  root 'rank#show_rank'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :films, :join_table => :films_categories  # def serializable_hash(options={})
  #   options = { 
  #     :include => {:user => {:only => [:email, :id]}, 
  #     :only => [:title, :id]
  #   }.update(options)
  #   super(options)
  # end

end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
    has_and_belongs_to_many :showing_films, -> { select('cinema_showings.*, films.id, films.name, films.duration, films.released_date, films.trailer_link') }, :class_name=>"Film", :join_table =>:cinema_showings
    has_many :screens
    def current_films
        d=Date.today
        self.showing_films#.where(":on_date < ? and :off_date> ?", d, d)
    end
end

app/models/cinema_showing.rb
class CinemaShowing < ActiveRecord::Base
  belongs_to :cinema
  belongs_to :film
end

app/models/dislike.rb
class Dislike < ActiveRecord::Base
  belongs_to :user
  belongs_to :film

  def self.count_dislike_by_film fid
    Dislike.where(:film_id=>fid).count
  end
end

app/models/film.rb
class Film < ActiveRecord::Base
  has_and_belongs_to_many :on_showing_cinemas, :class_name=>"Cinema", :join_table =>:cinema_showings
  has_and_belongs_to_many :liked_users, :class_name=>"User", :join_table =>:likes
  has_many :likes
  has_many :dislikes
  has_many :screen_likes
  has_many :screen_dislikes
  # belongs_to :category
  has_many :posters
  has_and_belongs_to_many :categories, :join_table => :films_categories
  def basic_info
    self.to_json(:include=>[{:categories=>{:only=>:name}},{:posters=>{:except=>:updated_at}}], 
        :except=>[:created_at, :updated_at])
  end

  def self.search_films film_name
    Film.where("lower(name) like ?", "%#{film_name.downcase}%")
  end

  def self.online_films
    Film.where(:online=>true).to_json(:include=>[{:categories=>{:only=>:name}},{:posters=>{:except=>:updated_at}}], 
        :except=>[:created_at, :updated_at])
  end

  def likes_and_dislikes uid
    likes=Like.where(film_id: self.id).count
    dislikes=Dislike.where(film_id: self.id).count
    like_by_me=Like.where(film_id: self.id, user_id: uid).count
    dislike_by_me=Dislike.where(film_id: self.id, user_id: uid).count
    {
      likes: likes,
      dislikes: dislikes,
      like_by_me: like_by_me,
      dislike_by_me: dislike_by_me
    }
  end

end
   

app/models/films_category.rb
class FilmsCategory < ActiveRecord::Base
  belongs_to :film
  belongs_to :category
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :film

  def self.count_like_by_film fid
    Like.where(:film_id=>fid).count
  end


end

app/models/poster.rb
class Poster < ActiveRecord::Base
  belongs_to :film
end

app/models/screen.rb
class Screen < ActiveRecord::Base
  belongs_to :cinema
  has_many :screen_likes
  has_many :screen_dislikes

  def likes_and_dislikes(uid,fid)
    likes=ScreenLike.where(screen_id: self.id,film_id: fid).count
    dislikes=ScreenDislike.where(screen_id: self.id,film_id: fid).count
    like_by_me=ScreenLike.where(screen_id: self.id, user_id: uid,film_id: fid).count
    dislike_by_me=ScreenDislike.where(screen_id: self.id, user_id: uid,film_id: fid).count
    {
      likes: likes,
      dislikes: dislikes,
      like_by_me: like_by_me,
      dislike_by_me: dislike_by_me
    }
  end
end

app/models/screen_dislike.rb
class ScreenDislike < ActiveRecord::Base
  belongs_to :user
  belongs_to :screen
  belongs_to :film
end

app/models/screen_like.rb
class ScreenLike < ActiveRecord::Base
  belongs_to :user
  belongs_to :screen
  belongs_to :film
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :liked_films, :class_name=>"Film", :join_table =>:likes
  before_create :generate_authentication_token!
  # belongs_to :default_cinema, :class_name=>"Cinema"
  validates :auth_token, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def default_cinema
    return self.cinema_id.blank? ? [] : Cinema.find(self.cinema_id)
  end

  def default_cinema_screen
    return self.cinema_id.blank? ? [] : Cinema.find(self.cinema_id).screens
  end

  def generate_authentication_token!
    begin 
      self.auth_token=Devise.friendly_token
    end while self.class.exists?(auth_token: auth_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  include Authenticable
end

app/controllers/concerns/authenticable.rb
module Authenticable
    #override Devise current_user
    def current_user
      @current_user ||= User.find_by(auth_token: request.headers['Authorization'])
    end

    def authenticate_with_token!
      render json: {errors: "not authenticated"}, status: :unauthorized unless current_user.present?
    end
end

app/controllers/rank_controller.rb
class RankController < ApplicationController
  def show_rank
    @films=Film.all.map do |f|
        {film_id: f.id, film_name: f.name, film_likes: f.likes.count, film_dislikes: f.dislikes.count}
    end
    @screens=Screen.all.map do |s|
       {screen_name: s.cinema.name+" screen "+s.number, screen_likes: s.screen_likes.count, screen_dislikes: s.screen_dislikes.count}
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: {film_rank: @films, screen_rank: @screens} }
    end

  end

  def film_screens
    @film=Film.find(params[:film_id])
    _screen_likes=@film.screen_likes.group(:screen_id).count
    _screen_dislikes=@film.screen_dislikes.group(:screen_id).count
    @flim_screen_likes=_screen_likes.map do |k,v|
        _sc=Screen.find(k)
        {screen: _sc.cinema.name+" screen "+_sc.number, likes: v}
    end
    @flim_screen_dislikes=_screen_dislikes.map do |k,v|
        _sc=Screen.find(k)
        {screen: _sc.cinema.name+" screen "+_sc.number, dislikes: v}
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: {screen_likes: @flim_screen_likes, screen_dislikes: @flim_screen_dislikes} }
    end
  end
end

app/helpers/api/v1/base_helper.rb
module Api::V1::BaseHelper
end

app/helpers/api/v1/cinema_helper.rb
module Api::V1::CinemaHelper
end

app/helpers/api/v1/films_helper.rb
module Api::V1::FilmsHelper
end

app/helpers/api/v1/like_helper.rb
module Api::V1::LikeHelper
end

app/helpers/api/v1/rank_helper.rb
module Api::V1::RankHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rank_helper.rb
module RankHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rank/_film_screen_dislike_table.html.erb
<table class='display datatable'>
    <thead>
        <tr>
            <th>Screen</th>
            <th><%= fa_icon "thumbs-o-down" %></th>
        </tr>
    </thead>

    <tbody>
        <% @flim_screen_dislikes.each do |f| %>
        <tr>
            <td><%= f[:screen] %></td>
            <td><%= f[:dislikes] %></td>
        </tr>
        <%end%>
    </tbody>
</table>

app/views/rank/_film_screen_like_table.html.erb
<table class='display datatable'>
    <thead>
        <tr>
            <th>Screen</th>
            <th><%= fa_icon "thumbs-o-up" %></th>
        </tr>
    </thead>

    <tbody>
        <% @flim_screen_likes.each do |f| %>
        <tr>
            <td><%= f[:screen] %></td>
            <td><%= f[:likes] %></td>
        </tr>
        <%end%>
    </tbody>
</table>

app/views/rank/_movie_table.html.erb
<table class='display datatable'>
    <thead>
        <tr>
            <th>Movie</th>
            <th><%= fa_icon "thumbs-o-up" %>   Up <b></b></th>
            <th><%= fa_icon "thumbs-o-down"%>   Down</th>
        </tr>
    </thead>

    <tbody>
        <% @films.each do |f| %>
        <tr>
            <td><%= link_to f[:film_name], show_flim_screen_preference_path(:film_id=>f[:film_id]) %></td>
            <td><%= f[:film_likes] %></td>
            <td><%= f[:film_dislikes] %></td>
        </tr>
        <%end%>
    </tbody>
</table>

app/views/rank/_screen_table.html.erb
<table class='display datatable'>
    <thead>
        <tr>
            <th>Screen</th>
            <th><%= fa_icon "thumbs-o-up" %>   Up <b></b></th>
            <th><%= fa_icon "thumbs-o-down"%>   Down</th>
        </tr>
    </thead>

    <tbody>
        <% @screens.each do |s| %>
        <tr>
            <td><%= s[:screen_name] %></td>
            <td><%= s[:screen_likes] %></td>
            <td><%= s[:screen_dislikes] %></td>
        </tr>
        <%end%>
    </tbody>
</table>

app/views/rank/film_screens.html.erb
<div class='panel panel-default'>
    <div class='panel-heading text-center'>
        <b><%=@film.name%></b>
    </div>
    <div class='panel-body'>
        <div class="row">
            <div class='col-xs-6'>
                <%= render 'film_screen_like_table'%>
            </div>
            <div class='col-xs-6'>
                <%= render 'film_screen_dislike_table'%>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$('.datatable').DataTable({
    "order": [[ 1, "desc" ]]
  // ajax: ...,
  // autoWidth: false,
  // pagingType: 'full_numbers',
  // processing: true,
  // serverSide: true,

  // Optional, if you want full pagination controls.
  // Check dataTables documentation to learn more about available options.
  // http://datatables.net/reference/option/pagingType
});
</script>

app/views/rank/show_rank.html.erb
<div class="row">
    <div class='col-xs-6'>
        <div class='panel panel-default'>
            <div class='panel-heading'>
                Movie Ranking            
            </div>
            <div class='panel-body'>
                <%= render 'movie_table'%>
            </div>
        </div>
    </div>
    <div class='col-xs-6'>
        <div class='panel panel-default'>
            <div class='panel-heading'>
                Screen Ranking            
            </div>
            <div class='panel-body'>
                <%= render 'screen_table'%>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$('.datatable').DataTable({
    "order": [[ 1, "desc" ]]
  // ajax: ...,
  // autoWidth: false,
  // pagingType: 'full_numbers',
  // processing: true,
  // serverSide: true,

  // Optional, if you want full pagination controls.
  // Check dataTables documentation to learn more about available options.
  // http://datatables.net/reference/option/pagingType
});
</script>